/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan1;

/**
 *
 * @author user
 */
public class pembayarann extends javax.swing.JFrame {

    /**
     * Creates new form pembayarann
     */
    public pembayarann() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtB4 = new javax.swing.JTextField();
        txtB3 = new javax.swing.JTextField();
        txtB2 = new javax.swing.JTextField();
        txtB1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 140, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Diskon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 260, 50, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Harga Barang 4");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 90, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 90, 16);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Harga Barang 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 140, 90, 16);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Harga Barang 1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 100, 90, 16);

        txtDiskon.setBackground(new java.awt.Color(102, 255, 204));
        txtDiskon.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(170, 250, 330, 30);

        txtB4.setBackground(new java.awt.Color(102, 255, 204));
        txtB4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txtB4);
        txtB4.setBounds(170, 210, 330, 30);

        txtB3.setBackground(new java.awt.Color(102, 255, 204));
        txtB3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txtB3);
        txtB3.setBounds(170, 170, 330, 30);

        txtB2.setBackground(new java.awt.Color(102, 255, 204));
        txtB2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txtB2);
        txtB2.setBounds(170, 130, 330, 30);

        txtB1.setBackground(new java.awt.Color(102, 255, 204));
        txtB1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txtB1);
        txtB1.setBounds(170, 90, 330, 30);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 310, 80, 26);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 310, 71, 26);

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 310, 73, 25);

        Hasil.setBackground(new java.awt.Color(102, 255, 204));
        Hasil.setColumns(20);
        Hasil.setFont(new java.awt.Font("Fake Receipt", 0, 12)); // NOI18N
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 350, 440, 160);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan1/mesin.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 550);

        setSize(new java.awt.Dimension(614, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int b1 = Integer.valueOf(txtB1.getText());
        int b2 = Integer.valueOf(txtB2.getText());
        int b3 = Integer.valueOf(txtB3.getText());
        int b4 = Integer.valueOf(txtB4.getText());
        int Diskon = Integer.valueOf(txtDiskon.getText());

        String a, c, e;
        int T, b, d;
        T = b1+b2+b3+b4;
        a = ""+T;

        if (Diskon == 100){
            b=T/100 * 100;
            c = ""+b;
            d = T - b;
            e = ""+d;
        }else if (Diskon == 50){
            b=T/100 * 50;
            c = ""+b;
            d = T - b;
            e = ""+d;

        }else if (Diskon == 25){
            b=T/100 * 25;
            c = ""+b;
            d = T - b;
            e = ""+d;
        }else if (Diskon == 75){
            b=T/100 * 75;
            c = ""+b;
            d = T - b;
            e = ""+d;

        }else {
            c = "Tidak Ada Diskon";
            e = ""+T;
        }

        Hasil.setText(       "Harga Barang 1  : "+b1+
            "\nHarga Barang 2  : "+b2+
            "\nHarga Barang 3  : "+b3+
            "\nHarga Barang 4  : "+b4+
            "\nTotal Harga     : "+a+
            "\nDiskon Anda     : "+c+
            "\nTotal Bayar     : "+e);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtB1.setText("");
        txtB2.setText("");
        txtB3.setText("");
        txtB4.setText("");
        txtDiskon.setText("");
        Hasil.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayarann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayarann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtB3;
    private javax.swing.JTextField txtB4;
    private javax.swing.JTextField txtDiskon;
    // End of variables declaration//GEN-END:variables
}
