/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Binner;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Tugas extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    public Tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBiner = new javax.swing.JTextField();
        txtDesimal = new javax.swing.JTextField();
        btnTipeKonversi = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KONVERTER BILANGAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 420, 60);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BINER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 120, 70, 20);

        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DESIMAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 120, 100, 20);

        txtBiner.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtBiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBinerActionPerformed(evt);
            }
        });
        getContentPane().add(txtBiner);
        txtBiner.setBounds(380, 150, 180, 30);

        txtDesimal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(txtDesimal);
        txtDesimal.setBounds(80, 150, 180, 30);

        btnTipeKonversi.setBackground(new java.awt.Color(0, 255, 0));
        btnTipeKonversi.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnTipeKonversi.setText("KONVERSI");
        btnTipeKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipeKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTipeKonversi);
        btnTipeKonversi.setBounds(170, 220, 310, 30);

        btn.setBackground(new java.awt.Color(0, 0, 255));
        btn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn.setText("< = >");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn);
        btn.setBounds(280, 150, 80, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Binner/3556273a597fb81.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 330);

        setSize(new java.awt.Dimension(659, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBinerActionPerformed

    private void btnTipeKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipeKonversiActionPerformed
  try {   
           
            if(txtBiner.getText().isEmpty()){
                int desi = Integer.valueOf(txtDesimal.getText());
                
                String bin = Integer.toBinaryString(desi);
                txtBiner.setText(bin);
            } else {
                String biner = txtBiner.getText();
                
                int des = Integer.parseInt(biner, 2);
                txtDesimal.setText(String.valueOf(des));
            }

           
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Input tidak valid: " + e.getMessage()); 

        } finally {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(true);
  }
    }//GEN-LAST:event_btnTipeKonversiActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed

        if(btn.getText().equals("< = >")){
            btn.setText("< = >");
        } else {
            btn.setText("< = >");
        }
       
        if(btn.getText().equals("< = >")){
            txtBiner.setEnabled(false);
            txtBiner.setText("");
            txtDesimal.setEnabled(true);
        } else {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(false);
            txtDesimal.setText("");
                
        }
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnTipeKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBiner;
    private javax.swing.JTextField txtDesimal;
    // End of variables declaration//GEN-END:variables
}
